### ISSUE TITLE
requests.exceptions.MissingSchema: Invalid URL '/saml2/idp/sso': No scheme supplied. Perhaps you meant http:///saml2/idp/sso?

### ISSUE THREAD

**Issue by machacekondra** [machacekondra/requests-sap#1]
You may receive such an exeception:
```python
Traceback (most recent call last):
  File "/tmp/main.py", line 7, in <module>
    r = requests.get(
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 652, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/omachace/.local/lib/python3.10/site-packages/requests_sap/sap.py", line 60, in handle_response
    response = self._next_step(response, history)
  File "/home/omachace/.local/lib/python3.10/site-packages/requests_sap/sap.py", line 43, in _next_step
    next_response = requests.post(
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 443, in prepare_request
    p.prepare(
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/saml2/idp/sso': No scheme supplied. Perhaps you meant http:///saml2/idp/sso?

```

This is because of wrong credentials. Need to verify the response from step4 and parse the output and print proper error message to user.

**Comment by fnschmidt** [comment]
Hello, I would love to use this module, but I‘m getting this exact exception.

I have verified that the correct username and password are passed (as regular strings).
They work when logging in regularly.

I‘m using the example code snippet from the README.

Do you know anything I could try to diagnose why it‘s not working?

**Comment by machacekondra** [comment]
Do you use Universal ID or Suser as username?
I can reproduce only when username or password is invalid, for example:
```bash
omachace ~/workspace/requests-sap (master) $ export LP_USERNAME=x
omachace ~/workspace/requests-sap (master) $ export LP_PASSWORD=y
omachace ~/workspace/requests-sap (master) $ cat main2.py 
import json
import os
import requests

from requests_sap import SAPAuth

r = requests.get(
    "https://launchpad.support.sap.com/services/odata/svt/swdcuisrv/ObjectSet('0030000000103162022')",
    auth=SAPAuth(username=os.environ['LP_USERNAME'], password=os.environ['LP_PASSWORD']),
    headers={'Accept': 'application/json'}
)

data = json.loads(r.text)
print(data['d']['Title'] + ' is ' + data['d']['Status'])

omachace ~/workspace/requests-sap (master) $ python main2.py 
Traceback (most recent call last):
  File "/home/omachace/workspace/requests-sap/main2.py", line 7, in <module>
    r = requests.get(
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 652, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/omachace/workspace/requests-sap/requests_sap/sap.py", line 109, in handle_response
    response = self._next_step(response, history)
  File "/home/omachace/workspace/requests-sap/requests_sap/sap.py", line 47, in _next_step
    next_response = requests.post(
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 443, in prepare_request
    p.prepare(
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/saml2/idp/sso': No scheme supplied. Perhaps you meant http:///saml2/idp/sso?
```

If you are using the environment variable for username/password just double check it's properly passed to the script. If it really is, can you please share the traceback?

**Comment by fnschmidt** [comment]
Thank you for your help! My mistake was using the email address as username. After passing the S-User, it works.

Perhaps you could mention that in the README, that way others won’t make the same mistake.

**Comment by machacekondra** [comment]
Actually since version `0.0.6` it should work even with e-mail address, that version added Universal ID support. What version did you use?

**Comment by olfolfolf** [comment]
I can confirm, S-User works with latest version - E-Mail Adress leads to error above.

**Comment by alederono** [comment]
I can confirm the example works with the mail address used for universal id.
